# Generated by Django 3.0.5 on 2020-06-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_brief_description', models.CharField(max_length=200)),
                ('report_nature', models.CharField(max_length=15)),
                ('report_full_description', models.TextField()),
                ('reporter_background', models.CharField(max_length=25)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('report_date', models.CharField(max_length=12)),
                ('report_time', models.CharField(max_length=12)),
                ('report_time_frame', models.CharField(max_length=120)),
                ('report_response_bodies', models.CharField(blank=True, max_length=255)),
                ('report_video_link', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
