# Generated by Django 3.0.5 on 2020-06-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0004_deploymentimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='report_image',
        ),
        migrations.AlterField(
            model_name='deploymentimages',
            name='file',
            field=models.ImageField(upload_to='deployment/images/'),
        ),
    ]
