# Generated by Django 3.0.5 on 2020-06-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0005_auto_20200622_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentimages',
            name='title',
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_number',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploymentimages',
            name='deployment_number',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
