# Generated by Django 3.0.5 on 2020-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0007_auto_20200622_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='report_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
