# Generated by Django 3.0.5 on 2020-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0009_deployment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='report_platform',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
