# Generated by Django 3.0.5 on 2020-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0011_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_location',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
