# Generated by Django 3.0.5 on 2020-07-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0013_customuser_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='deployment',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
