# Generated by Django 3.0.5 on 2020-07-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0014_auto_20200721_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
