# Generated by Django 3.0.5 on 2020-07-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0015_auto_20200725_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_response_body',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
