# Generated by Django 3.0.5 on 2020-07-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdusers', '0016_customuser_is_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='response_bodies',
            field=models.CharField(blank=True, choices=[('1', 'ghpolice@gh.com'), ('2', 'nadmo.com'), ('3', 'nafdac.com')], max_length=50),
        ),
    ]
